### ISSUE TITLE
How to reset zoom?

### ISSUE THREAD

**Issue by SeanStewart37** [chartjs/Chart.Zoom.js#17]
I'm removing and adding datasets that have completely different X and Y axis data.  After a user zooms in, the chart doesn't reset to the new perspective.  Is there a way to force a reset?

**Comment by etimberg** [comment]
@SeanStewart37 this is not currently possible. I'd be happy to merge a PR adding this functionality.

Essentially what would need to happen is that the original config min/max need to be stored (if specified) and then on reset either put those back or remove them completely

**Comment by pml984** [comment]
@SeanStewart37 This should be addressed in PR #28.

@etimberg Would it be possible to push a new release to NPM?

**Comment by etimberg** [comment]
@pml984 I will look into pushing a new release soon

**Comment by LipSoft** [comment]
I reset zoom like this -->
function resetZoom() {
			window.scatterChart.resetZoom()			
			
		}

var ctx = $("#myChart");				
window.scatterChart = new Chart(ctx, {});

also 1 thing i do when i build a new graph is remove the canvas and add again to the div

**Comment by etimberg** [comment]
Closing as resolved in #28
