### ISSUE TITLE
Line behaviour at chart area edges when zoomed/panned

### ISSUE THREAD

**Issue by jachstet-sea** [chartjs/Chart.Zoom.js#2]
Hi, thanks for implementing this feature!
However, there is a problem with the lines in the scatter graph at the edge of the chartArea when panned and/or zoomed. This can be observed with the "zoom.html" sample: When the graph is dragged around, the lines at the edge are beeing bent. This might not be too bad with bezier curves, but straight lines turn into curves which might not be desired.

**Comment by etimberg** [comment]
@jachstet-sea can you post a screenshot?

**Comment by jachstet-sea** [comment]
Let me try:
This is the orignal graph (after reloading and getting new random values):
![original](https://cloud.githubusercontent.com/assets/7993508/15071376/5e974764-138b-11e6-8147-65d3fc821cc3.png)
When I drag that to the right, the vertical line is not as curved as before:
![panned](https://cloud.githubusercontent.com/assets/7993508/15071401/84a29896-138b-11e6-977d-167c78994953.png)

I will try to get screenshots of the "straight line gets curved" as soon as I have a good sample ready

**Comment by etimberg** [comment]
oh, I know what happens: https://github.com/chartjs/Chart.js/blob/master/src/controllers/controller.line.js#L256-L261

**Comment by jachstet-sea** [comment]
Yep, that might well be the cause. Here's the example I meant with non-curved lines turnung curved:
https://gist.github.com/jachstet-sea/956ae41702a7487502996285387ec16b

Original (after reload - straight lines):
![straight](https://cloud.githubusercontent.com/assets/7993508/15071544/c14a9c52-138c-11e6-8b3e-fc7417e72cab.png)

After panning the lines are curved (the one on the left more than the other, but both are):
![curved](https://cloud.githubusercontent.com/assets/7993508/15071553/d2afd7f0-138c-11e6-94a1-90b54335cd72.png)

Not sure if it's the same cause

**Comment by jachstet-sea** [comment]
Also one can see in the panned screenshots that the tick labels can overlap when panned. Might be due to the niceNum-algorithm beeing overridden by setting the min and max ticks. Want a new issue report to keep things separated?

**Comment by etimberg** [comment]
@jachstet-sea definitely report the curved lines issue. The label overlapping one can be reported too, but I don't really know how to fix it. It happens because the first and last labels are always displayed

**Comment by BDominik** [comment]
Is this issue solved? Because I'm using chart js 2.7.2 and chart-js-zoom 0.6.5, and the straight lines are still being curves.

**Comment by BDominik** [comment]
I figured out. Just added tension : 0 to the straight line, so now its good
