### ISSUE TITLE
Zoom to Mouse Cursor

### ISSUE THREAD

**Issue by lysaght** [chartjs/Chart.Zoom.js#21]
Is there any plan to implement Zoom to Mouse Cursor functionality?  

Currently zoom, zooms to middle of plot.

The plugin is passing an argument named 'center' to the zoom functions which could be used to pass mouse pointer coordinates and calculate axis min and max etc which will zoom to cursor.

**Comment by etimberg** [comment]
@lysaght this is on my todo list. I think most of the functions that do the zooming already get passed the center point of the zoom, it just needs to be used.

I'm happy to merge a PR adding this

**Comment by lysaght** [comment]
I raised a PR.
