### ISSUE TITLE
Vertical Pan pans a little horizontally as well

### ISSUE THREAD

**Issue by lysaght** [chartjs/Chart.Zoom.js#23]
When panning directly vertical upwards using mouse it also pans a little to the left.  When panning directly vertical downwards it pans to the right.  Panning directly horizontal is fine.

This can replicated by adding Chart.Zoom plugin to Chart.js\samples\scatter.html using a recent version of Chrome.

**Comment by lysaght** [comment]
I've included fix for this in PR #22

**Comment by etimberg** [comment]
@lysaght great

**Comment by etimberg** [comment]
Fixed in #22
