### ISSUE TITLE
Add Ability to Zoom on a Range

### ISSUE THREAD

**Issue by pml984** [chartjs/Chart.Zoom.js#26]
A lot of the other charting frameworks contain the ability to zoom, but usually on a range. An example being highcharts:

http://www.highcharts.com/demo/line-time-series

This is maybe more of a questions that an issue, but was there any thought to add the ability to select a range similar to the link shown above? 

I did most of the work to currently add in this functionality, but it doesn't seem to fit in nicely with how this plugin in currently setup. The min and max are calculated are based upon the use of a wheel mouse as opposed to selecting a range. I didn't know if it would be better to create a separate plugin or try to move things around in this plugin and add in an option to add in this functionality.

**Comment by etimberg** [comment]
@pml984 I'm happy to look at PR if you can create one that adds this functionality.

**Comment by etimberg** [comment]
Done in #28
