### ISSUE TITLE
Straight lines turn curved when one of the end points is panned out of the chartarea

### ISSUE THREAD

**Issue by jachstet-sea** [chartjs/Chart.Zoom.js#3]
(Split from #2 since it's not certain if the cause is the same)

Sample html code:
https://gist.github.com/jachstet-sea/956ae41702a7487502996285387ec16b

Original (after reload - straight lines):
![straight](https://cloud.githubusercontent.com/assets/7993508/15071544/c14a9c52-138c-11e6-8b3e-fc7417e72cab.png)

After panning the lines are curved (the one on the left more than the other, but both are):
![curved](https://cloud.githubusercontent.com/assets/7993508/15071553/d2afd7f0-138c-11e6-94a1-90b54335cd72.png)

**Comment by etimberg** [comment]
Tested using the latest dev version of Chart.js and this has been fixed: https://codepen.io/anon/pen/ZOWbyy
