### ISSUE TITLE
Margins/padding causes drag zoom to be inaccurate

### ISSUE THREAD

**Issue by Skuhoo** [chartjs/Chart.Zoom.js#38]
When the canvas element is offset usings margins/padding the "selection" you make while drag zooming becomes inaccurate.

This is the [zoom-time](https://github.com/chartjs/Chart.Zoom.js/blob/master/samples/zoom-time.html) sample page with the body's left margin set to 100:
![image](https://cloud.githubusercontent.com/assets/20829776/18644974/5e4d66a4-7e79-11e6-8fd2-028308e36a31.png)

**Comment by etimberg** [comment]
Thanks for reporting this @Skuhoo

**Comment by gcmestre** [comment]
This problem also occurs with angular material side bar.

**Comment by niutski** [comment]
Could a new (minor?) release be made with the fix please?

**Comment by etimberg** [comment]
@niutski I will try and do this tonight

**Comment by niutski** [comment]
@etimberg cheers!

**Comment by etimberg** [comment]
Fixed in #48

**Comment by etimberg** [comment]
@niutski fixed in v0.3.0 which I've released. Would you be interested in helping to maintain the zoom plugin? I thought I'd ask since you were quick to fix the merge conflict and get that change merged

**Comment by niutski** [comment]
I can help out when possible :)
