### ISSUE TITLE
Is Chart.Zoom.js mobile-friendly?

### ISSUE THREAD

**Issue by m-oliv** [chartjs/Chart.Zoom.js#42]
I want to use Chart.Zoom.js to zoom / pan Chart.js charts in mobile devices. Is this currently possible?

**Comment by etimberg** [comment]
@m-oliv yes this is touch friendly. Chart.Zoom.js depends on HammerJS. It has full touch support for panning and uses a pinch gesture to zoom.

**Comment by m-oliv** [comment]
@etimberg Thanks for your prompt answer!
I tried to use the zoom feature both on desktop and mobile. As far as I could tell, the zoom feature works in the desktop, but when I switch to mobile I cannot zoom in / zoom out using the pinch gesture.
While experimenting, I noticed that your samples (included in the zip of your main repo) only work if I place the js files of HammerJS and ChartJS in a specific location:
**Chart.Zoom.js/node_modules/<HammerJS>**
**Chart.Zoom.js/node_modules/<ChartJS>**

So, is Chart.Zoom.js looking for HammerJS in a set location (as above), or should it work as long as I import this library in the page that uses Chart.Zoom.js?

**Comment by etimberg** [comment]
It should work as long as hammerjs is included in the page

**Comment by m-oliv** [comment]
@etimberg OK. Thanks! I'll look into my code again!

**Comment by LipSoft** [comment]
I testes on my project and it works fine pan and zoom

**Comment by rupalpatel0008** [comment]
Its not working properly in mobile devices.
Tested with ionic 2 project

**Comment by JanOonk** [comment]
Tip: Don't forget to FIRST include hammer BEFORE chart.js and zoom plugin:
```
    <script src="js/hammer.min.js"></script>
    <script src="js/chart.min.js"></script>
    <script src="js/chartjs-plugin-zoom.min.js"></script>
```
